/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.EmployeeDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employees;

/**
 *
 * @author Thain
 */
public class FrmControleUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastroFuncionario
     */
    public FrmControleUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabelCadastroClientes = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelControleFuncionarios2 = new javax.swing.JPanel();
        jLabelNome2 = new javax.swing.JLabel();
        txtNomeCadastro = new javax.swing.JTextField();
        jLabelEmail2 = new javax.swing.JLabel();
        txtEmailCadastro = new javax.swing.JTextField();
        jLabelCodigo6 = new javax.swing.JLabel();
        jLabelCpf2 = new javax.swing.JLabel();
        txtCpfCadastro = new javax.swing.JFormattedTextField();
        jLabelCelular2 = new javax.swing.JLabel();
        txtCelularCadastro = new javax.swing.JFormattedTextField();
        txtSenhaCadastro = new javax.swing.JPasswordField();
        txtConfirmacaoSenhaCadastro = new javax.swing.JPasswordField();
        jLabelCodigo7 = new javax.swing.JLabel();
        jLabelCodigo8 = new javax.swing.JLabel();
        cbbTipoAcessoCadastro = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelNome3 = new javax.swing.JLabel();
        txtConsultaFuncionario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();
        btnPesquisarFuncionario = new javax.swing.JButton();
        btnCadastrar1 = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Funcionários");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setToolTipText("");

        jLabelCadastroClientes.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelCadastroClientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadastroClientes.setText("Controle de Usuários");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelCadastroClientes)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabelCadastroClientes)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanelControleFuncionarios2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNome2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNome2.setText("Nome:");

        txtNomeCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelEmail2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEmail2.setText("E-mail:");

        txtEmailCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmailCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabelCodigo6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCodigo6.setText("Senha");

        jLabelCpf2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCpf2.setText("CPF:");

        try {
            txtCpfCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCpfCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        jLabelCelular2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCelular2.setText("Celular:");

        try {
            txtCelularCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelularCadastro.setToolTipText("");
        txtCelularCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCelularCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });

        txtSenhaCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSenhaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        txtConfirmacaoSenhaCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConfirmacaoSenhaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmacaoSenhaCadastroActionPerformed(evt);
            }
        });
        txtConfirmacaoSenhaCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConfirmacaoSenhaKeyPressed(evt);
            }
        });

        jLabelCodigo7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCodigo7.setText("Confirmar Senha");

        jLabelCodigo8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCodigo8.setText("Acesso");

        cbbTipoAcessoCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbTipoAcessoCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USUÁRIO", "ADMIN" }));
        cbbTipoAcessoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTipoAcessoActionPerformed(evt);
            }
        });

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setText("LIMPAR");
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelControleFuncionarios2Layout = new javax.swing.GroupLayout(jPanelControleFuncionarios2);
        jPanelControleFuncionarios2.setLayout(jPanelControleFuncionarios2Layout);
        jPanelControleFuncionarios2Layout.setHorizontalGroup(
            jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleFuncionarios2Layout.createSequentialGroup()
                .addGroup(jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelControleFuncionarios2Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(txtCpfCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jLabelCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtCelularCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelControleFuncionarios2Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelEmail2)
                                .addComponent(jLabelCodigo6)
                                .addComponent(jLabelCodigo8))
                            .addGroup(jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelControleFuncionarios2Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbbTipoAcessoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanelControleFuncionarios2Layout.createSequentialGroup()
                                            .addComponent(txtSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabelCodigo7)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtConfirmacaoSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanelControleFuncionarios2Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelControleFuncionarios2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnCadastrar)
                        .addGap(26, 26, 26)
                        .addComponent(btnLimpar))
                    .addGroup(jPanelControleFuncionarios2Layout.createSequentialGroup()
                        .addGroup(jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelControleFuncionarios2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabelNome2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControleFuncionarios2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelCpf2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jPanelControleFuncionarios2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCadastrar, btnLimpar});

        jPanelControleFuncionarios2Layout.setVerticalGroup(
            jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleFuncionarios2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome2)
                    .addComponent(txtNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelularCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCelular2)
                    .addComponent(jLabelCpf2)
                    .addComponent(txtCpfCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail2)
                    .addComponent(txtEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo6)
                    .addComponent(txtSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodigo7)
                    .addComponent(txtConfirmacaoSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo8)
                    .addComponent(cbbTipoAcessoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanelControleFuncionarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanelControleFuncionarios2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCadastrar, btnLimpar});

        jTabbedPane1.addTab("Cadastrar Usuário", jPanelControleFuncionarios2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNome3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNome3.setText("Nome:");

        txtConsultaFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConsultaFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConsultaFuncionarioFocusLost(evt);
            }
        });

        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Celular", "E-mail"
            }
        ));
        jScrollPane1.setViewportView(tabelaFuncionarios);

        btnPesquisarFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisarFuncionario.setText("Pesquisar");
        btnPesquisarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarFuncionarioMouseClicked(evt);
            }
        });
        btnPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarFuncionarioActionPerformed(evt);
            }
        });

        btnCadastrar1.setText("EXCLUIR");
        btnCadastrar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtConsultaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnPesquisarFuncionario))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btnCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome3)
                    .addComponent(txtConsultaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Excluir Usuáro", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 151, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cbbTipoAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTipoAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTipoAcessoActionPerformed

    private void txtConfirmacaoSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmacaoSenhaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmacaoSenhaKeyPressed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtConsultaFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConsultaFuncionarioFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtConsultaFuncionarioFocusLost

    private void btnPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarFuncionarioActionPerformed
        // TODO add your handling code here:

        String nome = "%" + txtConsultaFuncionario.getText() + "%";
        EmployeeDAO dao = new EmployeeDAO();

        DefaultTableModel dados = (DefaultTableModel) tabelaFuncionarios.getModel();
        dados.setNumRows(0);

        for (Employees p : dao.buscaFuncionariosPorNome(nome)) {
            dados.addRow(new Object[]{p.getId(), p.getName(), p.getCpf(), p.getCelular(), p.getEmail()

            });

        }
    }//GEN-LAST:event_btnPesquisarFuncionarioActionPerformed

    private void btnPesquisarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarFuncionarioMouseClicked
        // TODO add your handling code here:

        String nome = "%" + txtConsultaFuncionario.getText() + "%";
        EmployeeDAO dao = new EmployeeDAO();

        DefaultTableModel dados = (DefaultTableModel) tabelaFuncionarios.getModel();
        dados.setNumRows(0);

        for (Employees p : dao.buscaFuncionariosPorNome(nome)) {
            dados.addRow(new Object[]{p.getId(), p.getName(), p.getCpf(), p.getCelular(), p.getEmail()

            });

        }

    }//GEN-LAST:event_btnPesquisarFuncionarioMouseClicked

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        // TODO add your handling code here: 
        EmployeeDAO dao = new EmployeeDAO();

        Employees obj = new Employees();

        obj.setName(txtNomeCadastro.getText().toUpperCase());
        obj.setCpf(txtCpfCadastro.getText().toUpperCase());
        obj.setCelular(txtCelularCadastro.getText());
        obj.setEmail(txtEmailCadastro.getText().toUpperCase());
        obj.setPassword(txtSenhaCadastro.getText());
        obj.setTipoAcesso(cbbTipoAcessoCadastro.getSelectedItem().toString());

        if (txtSenhaCadastro.getText().equals(txtConfirmacaoSenhaCadastro.getText())) {
            dao.cadastrarFuncionarios(obj);
        } else {
            JOptionPane.showMessageDialog(null, "As senhas não conferem, digite novamente!");

        }

    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void txtConfirmacaoSenhaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmacaoSenhaCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmacaoSenhaCadastroActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtNomeCadastro.setText("");
        txtCpfCadastro.setText("");
        txtCelularCadastro.setText("");
        txtEmailCadastro.setText("");
        txtSenhaCadastro.setText("");
        txtConfirmacaoSenhaCadastro.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmControleUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmControleUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmControleUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmControleUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmControleUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCadastrar1;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisarFuncionario;
    private javax.swing.JComboBox<String> cbbTipoAcessoCadastro;
    private javax.swing.JLabel jLabelCadastroClientes;
    private javax.swing.JLabel jLabelCelular2;
    private javax.swing.JLabel jLabelCodigo6;
    private javax.swing.JLabel jLabelCodigo7;
    private javax.swing.JLabel jLabelCodigo8;
    private javax.swing.JLabel jLabelCpf2;
    private javax.swing.JLabel jLabelEmail2;
    private javax.swing.JLabel jLabelNome2;
    private javax.swing.JLabel jLabelNome3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanelControleFuncionarios2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaFuncionarios;
    private javax.swing.JFormattedTextField txtCelularCadastro;
    private javax.swing.JPasswordField txtConfirmacaoSenhaCadastro;
    private javax.swing.JTextField txtConsultaFuncionario;
    private javax.swing.JFormattedTextField txtCpfCadastro;
    private javax.swing.JTextField txtEmailCadastro;
    private javax.swing.JTextField txtNomeCadastro;
    private javax.swing.JPasswordField txtSenhaCadastro;
    // End of variables declaration//GEN-END:variables

}
